; Per-module settings, written by Customize Kerf.
; Hover 0 none, 1 fade in, 2 fade out, 3 hide. Align 0 follow position, 1 left, 2 centre, 3 right, 4 top, 5 bottom.
; ClockLayout 0 classic, 1 vertical, 2 horizontal. CPU/GPULayout 0 horizontal, 1 vertical.
[Variables]
ClockSize=100
ClockAutoScale=1.00
ClockTrans=0
ClockHover=0
CPUSize=100
CPUAutoScale=1.00
CPUTrans=0
CPUHover=0
GPUSize=100
GPUAutoScale=1.00
GPUTrans=0
GPUHover=0
ClockAlign=0
CPUAlign=0
GPUAlign=0
ClockShowTime=1
ClockShowSeconds=1
ClockShowPulse=1
ClockShowDay=1
ClockShowDate=1
ClockLayout=0
CPULayout=0
GPULayout=0
