; Per-module settings, written by Customize Kerf.
; Hover 0 none, 1 fade in, 2 fade out, 3 hide. Align 0 follow position, 1 left, 2 centre, 3 right, 4 top, 5 bottom.
[Variables]
ClockSize=100
ClockTrans=0
ClockHover=0
CPUSize=100
CPUTrans=0
CPUHover=0
GPUSize=100
GPUTrans=0
GPUHover=0
ClockAlign=0
CPUAlign=0
GPUAlign=0
ClockShowTime=1
ClockShowSeconds=1
ClockShowWave=1
ClockShowDay=1
ClockShowDate=1
