[sBase]
AntiAlias=1
DynamicVariables=1
FontFace=#FontFace#
FontColor=#Ink#,(#A1#*#FadeK#)
InlineSetting=Shadow | 0 | 1 | 4 | #Halo#,(70*#FadeK#)

[sMono]
InlineSetting=Shadow | 0 | 1 | 3 | #Halo#,(150*#FadeK#)
FontFace=#MonoFace#
FontWeight=400
FontSize=(8*#Scale#)
FontColor=#Ink#,(#A3#*#FadeK#)
InlineSetting2=CharacterSpacing | 0 | #MicroTracking# | 0

[sHitBox]
Meter=Image
SolidColor=0,0,0,1
DynamicVariables=1
